#!/usr/bin/env python3
"""Does a PDF parse as well as the DOCX it was exported from?

The DOCX path had four live bugs that only a real file revealed - a missing
phone pattern, a dropped "CORE COMPETENCIES" heading, a job title read as an
industry, and a stated figure attributed to the wrong clause. None were visible
in the code and none were covered by a test. The PDF path had no test and no
fixture at all, so it is held to the same standard rather than assumed working
because a library is installed.

Both files are generated from test_resume.txt, so anything the PDF path loses is
a PDF problem and not a difference in the document. The bar is not "produced some
output": a PDF is allowed to differ in whitespace and line breaks, but it may not
lose a phone number, an email, a link, a skill or a job field, because those are
what a candidate's dossier is built from.

Both fixtures are generated by _make_pdf_fixture.py so the suite has no binary
dependency and the two can never drift apart.
"""
import io
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import resume_ingest as ing  # noqa: E402

DOCX = os.path.join(HERE, "test_resume.docx")
PDF = os.path.join(HERE, "test_resume.pdf")

fails = []


def check(label, condition, detail=""):
    print(("  PASS  " if condition else "  FAIL  ") + label
          + ("" if condition else "   %s" % (detail,)))
    if not condition:
        fails.append(label)


# Fixtures are generated, not committed as binaries.
if not (os.path.exists(DOCX) and os.path.exists(PDF)):
    subprocess.run([sys.executable, os.path.join(HERE, "_make_pdf_fixture.py")],
                   check=True, capture_output=True)

print("=== text extraction ===")
texts = {label: ing.extract_resume_text(path)
         for label, path in (("docx", DOCX), ("pdf", PDF))}
for label, text in texts.items():
    print("  %-5s %6d chars, %4d lines" % (label, len(text), text.count("\n") + 1))


def tokens(text):
    return re.findall(r"[A-Za-z0-9@.+#-]{2,}", text.casefold())


docx_tokens = tokens(texts["docx"])
pdf_token_set = set(tokens(texts["pdf"]))
missing = [t for t in docx_tokens if t not in pdf_token_set]
coverage = 100.0 * (len(docx_tokens) - len(missing)) / max(1, len(docx_tokens))
print("\n=== token coverage, docx -> pdf ===")
print("  %d docx tokens, %d absent from the pdf text (%.1f%% recovered)"
      % (len(docx_tokens), len(missing), coverage))
if missing:
    print("  missing: %s" % ", ".join(sorted(set(missing))[:20]))

print("\n=== signals, side by side ===")
results = {label: ing.ingest_resume(path)
           for label, path in (("docx", DOCX), ("pdf", PDF))}

for key in ("emails", "phones", "urls", "skills", "job_fields", "employment_hints"):
    a, b = results["docx"].get(key), results["pdf"].get(key)
    a_n = len(a) if isinstance(a, (list, dict)) else 0
    b_n = len(b) if isinstance(b, (list, dict)) else 0
    print("  %-17s docx=%-3d pdf=%-3d" % (key, a_n, b_n))

print("\n=== what a candidate would notice ===")
for label in ("docx", "pdf"):
    r = results[label]
    print("  %s" % label)
    for key in ("emails", "phones", "urls"):
        print("    %-8s %s" % (key, r.get(key)))
    print("    %-8s %s" % ("skills", (r.get("skills") or [])[:10]))
    print("    %-8s %s" % ("fields", r.get("job_fields")))
    hints = r.get("employment_hints") or []
    print("    %-8s %s" % ("jobs", [(h.get("company"), h.get("title"), h.get("start"))
                                     for h in hints[:4]]))

print("\n=== the assertions ===")
check("every docx token survives into the pdf text", not missing,
      "missing %d: %s" % (len(missing), sorted(set(missing))[:8]))
check("text coverage is at least 99%", coverage >= 99.0, "%.1f%%" % coverage)

for key in ("emails", "phones", "urls", "skills", "job_fields"):
    check("pdf keeps the same %s" % key,
          results["pdf"].get(key) == results["docx"].get(key),
          "docx=%r pdf=%r" % (results["docx"].get(key), results["pdf"].get(key)))

check("the pdf actually yields signals to compare",
      bool(results["pdf"].get("phones") or results["pdf"].get("skills")
           or results["pdf"].get("job_fields")),
      "an empty parse would pass every comparison above without testing anything")

print()
if fails:
    print("%d FAILED: %s" % (len(fails), "; ".join(fails)))
    sys.exit(1)
print("pdf parsing matches docx parsing")
